export interface LeagueSettings {
    total_rosters: number;
    status: string;
    sport: string;
    shard: number;
    settings: Settings;
    season_type: string;
    season: string;
    scoring_settings: ScoringSettings;
    roster_positions?: (string)[] | null;
    previous_league_id: string;
    name: string;
    metadata?: Metadata | null;
    loser_bracket_id?: null;
    league_id: string;
    last_transaction_id: number;
    last_read_id: string;
    last_pinned_message_id?: string | null;
    last_message_time: number;
    last_message_text_map?: null;
    last_message_id: string;
    last_message_attachment?: null;
    last_author_is_bot?: boolean | null;
    last_author_id: string;
    last_author_display_name: string;
    last_author_avatar: string;
    group_id?: null;
    draft_id: string;
    display_order: number;
    company_id?: null;
    bracket_id?: null;
    avatar?: string | null;
  }
  export interface Settings {
    max_keepers: number;
    draft_rounds: number;
    trade_review_days: number;
    squads: number;
    reserve_allow_dnr: number;
    capacity_override: number;
    pick_trading: number;
    disable_trades: number;
    taxi_years: number;
    taxi_allow_vets: number;
    best_ball: number;
    last_report: number;
    disable_adds: number;
    waiver_type: number;
    bench_lock: number;
    reserve_allow_sus: number;
    type: number;
    reserve_allow_cov: number;
    waiver_clear_days: number;
    daily_waivers_last_ran: number;
    waiver_day_of_week: number;
    start_week: number;
    playoff_teams: number;
    num_teams: number;
    reserve_slots: number;
    playoff_round_type: number;
    daily_waivers_hour: number;
    waiver_budget: number;
    reserve_allow_out: number;
    offseason_adds: number;
    playoff_seed_type: number;
    daily_waivers: number;
    divisions: number;
    playoff_week_start: number;
    daily_waivers_days: number;
    league_average_match: number;
    leg: number;
    trade_deadline: number;
    reserve_allow_doubtful: number;
    taxi_deadline: number;
    reserve_allow_na: number;
    taxi_slots: number;
    playoff_type: number;
  }
  export interface ScoringSettings {
    yds_allow_400_449?: number | null;
    yds_allow_550p?: number | null;
    yds_allow_100_199?: number | null;
    pass_2pt: number;
    pass_int: number;
    fgmiss: number;
    rec_yd: number;
    xpmiss: number;
    def_pr_td?: number | null;
    fgm_30_39: number;
    yds_allow_450_499?: number | null;
    blk_kick: number;
    pts_allow_7_13: number;
    ff: number;
    fgm_20_29: number;
    fgm_40_49: number;
    pts_allow_1_6: number;
    st_fum_rec: number;
    pass_sack?: number | null;
    yds_allow_500_549?: number | null;
    def_st_ff: number;
    st_ff: number;
    yds_allow_0_100?: number | null;
    yds_allow_350_399?: number | null;
    pts_allow_28_34: number;
    fgm_50p: number;
    fum_rec: number;
    def_td: number;
    fgm_0_19: number;
    int: number;
    pts_allow_0: number;
    pts_allow_21_27: number;
    rec_2pt: number;
    rec: number;
    xpm: number;
    st_td: number;
    def_st_fum_rec: number;
    def_st_td: number;
    sack: number;
    fum_rec_td: number;
    rush_2pt: number;
    rec_td: number;
    pts_allow_35p: number;
    pts_allow_14_20: number;
    rush_yd: number;
    fgm_yds_over_30?: number | null;
    pass_yd: number;
    pass_td: number;
    rush_td: number;
    def_kr_td?: number | null;
    fum_lost: number;
    yds_allow_200_299?: number | null;
    fum: number;
    safe: number;
    def_pr_yd?: number | null;
    kr_yd?: number | null;
    rec_30_39?: number | null;
    def_kr_yd?: number | null;
    bonus_rec_te?: number | null;
    rec_20_29?: number | null;
    rec_0_4?: number | null;
    pr_td?: number | null;
    kr_td?: number | null;
    rec_5_9?: number | null;
    rec_10_19?: number | null;
    pr_yd?: number | null;
    rec_40p?: number | null;
    fg_ret_yd?: number | null;
    tkl?: number | null;
    tkl_loss?: number | null;
    fgmiss_50p?: number | null;
    fgm_yds?: number | null;
    blk_kick_ret_yd?: number | null;
    pts_allow?: number | null;
    sack_yd?: number | null;
    bonus_rush_yd_100?: number | null;
    bonus_rush_rec_yd_200?: number | null;
    pass_fd?: number | null;
    bonus_rush_rec_yd_100?: number | null;
    yds_allow_300_349?: number | null;
    def_st_tkl_solo?: number | null;
    int_ret_yd?: number | null;
    def_pass_def?: number | null;
    rush_40p?: number | null;
    pass_td_40p?: number | null;
    bonus_rec_rb?: number | null;
    bonus_pass_cmp_25?: number | null;
    pass_cmp?: number | null;
    bonus_rec_yd_200?: number | null;
    qb_hit?: number | null;
    rush_fd?: number | null;
    bonus_pass_yd_300?: number | null;
    st_tkl_solo?: number | null;
    tkl_solo?: number | null;
    pass_att?: number | null;
    bonus_rush_yd_200?: number | null;
    pass_inc?: number | null;
    pass_cmp_40p?: number | null;
    fgmiss_30_39?: number | null;
    tkl_ast?: number | null;
    bonus_rush_att_20?: number | null;
    rush_att?: number | null;
    fgm?: number | null;
    fgmiss_40_49?: number | null;
    rush_td_40p?: number | null;
    rec_td_40p?: number | null;
    bonus_pass_yd_400?: number | null;
    fum_ret_yd?: number | null;
    pass_int_td?: number | null;
    bonus_rec_wr?: number | null;
    fgmiss_0_19?: number | null;
    yds_allow?: number | null;
    bonus_rec_yd_100?: number | null;
    def_2pt?: number | null;
    fgmiss_20_29?: number | null;
    rec_fd?: number | null;
  }
  export interface Metadata {
    division_2: string;
    division_1: string;
    division_2_avatar?: string | null;
    division_1_avatar?: string | null;
  }
  